- name: "👾 Bug"
  color: "e99695"
  description: "버그 관련"

- name: "🌎 Deploy"
  color: "c5def5"
  description: "배포"

- name: "🎨 Design"
  color: "efeeb3"
  description: "마크업 및 스타일링"

- name: "📑 Docs"
  color: "bfdadd"
  description: "문서 작성 및 수정"

- name: "✨ Feature"
  color: "e2caf4"
  description: "기능 구현"

- name: "🛠️ Refactor"
  color: "c2e0c6"
  description: "코드 리팩토링"

- name: "⚙️ Setting"
  color: "e2e2e2"
  description: "개발 환경 세팅"
